# Policy for: .github/workflows/publish.yml in DataDog/homebrew-lapdog
issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/homebrew-lapdog:pull_request

claim_pattern:
  event_name: pull_request_target
  job_workflow_ref: DataDog/homebrew-lapdog/\.github/workflows/publish\.yml@refs/heads/main
  ref: refs/heads/main
  repository: DataDog/homebrew-lapdog

permissions:
  contents: write
  pull_requests: write
