name: brew pr-pull

# Triggers when a PR gets labeled with `pr-pull`. Pulls bottle artifacts from
# the PR's tests workflow run, uploads them to a GitHub Release tied to the
# formula version, updates the formula's `bottle do` block on the PR, and
# pushes the result to the PR branch. Maintainer then merges the PR normally.

on:
  pull_request_target:
    types:
      - labeled

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: Issue dd-octo-sts token
        id: octo-sts
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        with:
          audience: dd-octo-sts
          scope: DataDog/homebrew-lapdog
          policy: self.pull_request_target.pr-pull

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@cf31444e770b9919bb21e695d66f56c39cfd3dee # master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@cf31444e770b9919bb21e695d66f56c39cfd3dee # master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ steps.octo-sts.outputs.token }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          brew pr-pull \
            --debug \
            --tap="${GITHUB_REPOSITORY}" \
            --workflows="tests.yml" \
            --artifact-pattern="bottles-*" \
            "${PR}"

      - name: Push commits
        uses: Homebrew/actions/git-try-push@cf31444e770b9919bb21e695d66f56c39cfd3dee # master
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          branch: ${{ github.event.pull_request.base.ref }}
